version: '2.0'

services:
  postgres:
    container_name: smart_farming_postgres
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123

  smart_farming:
    container_name: smart_farming
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/smart_farming/
    depends_on:
      - postgres